<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PromoterController;

/**
 * Promoter API
 * List or edit promoters with skills and groups
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */

 /**
 * get promotersPromoterIdGet
 * Summary: Read a promoter with skills
 * Notes: 
 * Output-Formats: [application/json]
 */
Route::get('/promoters/{promoterId}', [PromoterController::class, 'promotersPromoterIdGet']);

 /**
 * get promotersGet
 * Summary: List all promoters
 * Notes: 
 * Output-Formats: [application/json]
 */
Route::get('/promoters', [PromoterController::class, 'promotersGet']);

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});

