<?php
/**
 * Promoter API
 * List or edit promoters with skills and groups
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


 namespace App\Http\Controllers;

// use Illuminate\Support\Facades\Request; // auto-generated
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class PromoterController extends Controller
{
/**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation promotersPromoterIdGet
     *
     * Read a promoter.
     *
     * @param string $promoterId The unique identifier of the promoter (required)
     *
     * @return Http response
     */
    public function promotersPromoterIdGet(Int $promoterId)
    {
        // $input = Request::all();
        
        if (is_int($promoterId) === false) {
            return response('todo: error by non integer'); //todo: Define error by wrong type
        }

        $promoters = DB::select('select * from promoters where id = ? limit 1', [$promoterId]);

        if ($promoters === null) {
            return response('todo: return not found'); //todo: Define error by out of range id
        }

        foreach($promoters as $promoter) {
            return response($promoter->getName());
        }
    }


}
